// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     example:sdk

package wasi_cli_exit

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

//go:wasmimport wasi:cli/exit@0.3.0-rc-2026-03-15 exit
func wasm_import_exit(arg0 int32)

func Exit(status witTypes.Result[witTypes.Unit, witTypes.Unit]) {

	var option int32
	switch status.Tag() {
	case witTypes.ResultOk:

		option = int32(0)
	case witTypes.ResultErr:

		option = int32(1)
	default:
		panic("unreachable")
	}
	wasm_import_exit(option)

}
