// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     example:sdk

package wasi_cli_terminal_stdout

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"pkg/bindings/imports/wasi_cli_terminal_output"
	"runtime"
	"unsafe"
)

type TerminalOutput = wasi_cli_terminal_output.TerminalOutput

//go:wasmimport wasi:cli/terminal-stdout@0.3.0-rc-2026-03-15 get-terminal-stdout
func wasm_import_get_terminal_stdout(arg0 uintptr)

func GetTerminalStdout() witTypes.Option[*wasi_cli_terminal_output.TerminalOutput] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_get_terminal_stdout(returnArea)
	var option witTypes.Option[*wasi_cli_terminal_output.TerminalOutput]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[*wasi_cli_terminal_output.TerminalOutput]()
	case 1:

		option = witTypes.Some[*wasi_cli_terminal_output.TerminalOutput](wasi_cli_terminal_output.TerminalOutputFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}
