// Note: This file was NOT generated by componentize-go

package export_wasi_cli_run

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

var Exports struct {
	Run func() witTypes.Result[witTypes.Unit, witTypes.Unit]
}

func Run() witTypes.Result[witTypes.Unit, witTypes.Unit] {
	return Exports.Run()
}
