// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     example:sdk

package wasi_clocks_types

import ()

type Duration = uint64
