// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     foo:baz@0.1.0

package primary

import (
        witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
"unsafe"
"runtime"
)


//go:wasmimport primary get
func wasm_import_get(arg0 uintptr, arg1 uint32, arg2 uintptr) 

func Get(key string) string {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(witRuntime.Allocate(pinner, (2*4), 4))
        utf8 := unsafe.Pointer(unsafe.StringData(key))
pinner.Pin(utf8)
wasm_import_get(uintptr(utf8), uint32(len(key)), returnArea)
value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
result := value;
return result

}
